version: 2
updates:

- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
  open-pull-requests-limit: 25
  labels: [ ]

- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: "daily"
  open-pull-requests-limit: 25
  labels: [ ]

- package-ecosystem: "docker"
  directory: "/"
  schedule:
    interval: "daily"
  open-pull-requests-limit: 25
  labels: [ ]