maintenance:
  - any:
    - changed-files:
      - any-glob-to-any-file: ['**/*.csproj', '**/*.sln']

core:
  - any:
    - changed-files:
      - any-glob-to-any-file: ['BaseBotService/Core/**/*']

infrastructure:
  - any:
    - changed-files:
      - any-glob-to-any-file: ['**/Dockerfile', 'tools/**/*', '.editorconfig', '.gitattributes', '.gitignore', '.dockerignore', 'Honeycomb.lutconfig', '.github/**/*']

enhancement:
  - any:
    - changed-files:
      - any-glob-to-any-file: ['BaseBotService/**/*.cs']

documentation:
  - any:
    - changed-files:
      - any-glob-to-any-file: ['**/*.md', 'LICENSE', 'docs/**/*']

testing:
  - any:
    - changed-files:
      - any-glob-to-any-file: ['BaseBotServiceTests/**/*']
