namespace BaseBotService.Enumeration;

public enum Countries
{
    Unknown = 0,
    UnitedStates = 1,
    Canada = 2,
    UnitedKingdom = 3,
    Australia = 4,
    Germany = 5,
    France = 6,
    Brazil = 7,
    Mexico = 8,
    Netherlands = 9,
    Sweden = 10,
    Norway = 11,
    Denmark = 12,
    Finland = 13,
    Spain = 14,
    Italy = 15,
    Poland = 16,
    Russia = 17,
    Japan = 18,
    SouthKorea = 19,
    China = 20,
    India = 21,
    Turkey = 22,
    Indonesia = 23,
    Philippines = 24,
    Austria = 25,
    Swiss = 26,
}