name: 'CI'
on:
   push:
     branches: [ "main" ]
   pull_request:
jobs:
   build-test:
     runs-on: ubuntu-latest
     steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # avoid shallow clone to calculate semVer 
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.x'
          include-prerelease: true
      - name: Build with dotnet
        run: dotnet build --configuration Debug
      - name: Run tests with dotnet
        run: dotnet test --logger "trx;logfilename=testResults.trx"
      - uses: actions/upload-artifact@v3
        if: success() || failure()  # run this step even if previous step failed
        with:
           name: test-results
           path: ./**/*.trx
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
