name: 'Conventional Commits Validation'

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      # Please look up the latest version from
      # https://github.com/roseline124/action-semantic-pull-request/releases
      - uses: roseline124/action-semantic-pull-request@v3.5.4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Configure which types are allowed.
          # Default: https://github.com/commitizen/conventional-commit-types
          types: |
            fix
            feat
            bug
            docs
            refactor
            revert
            chor
            build
            config
            style
            perf
            test
            ci
          # Configure which scopes are allowed.
          # scopes: |
          #   core
          #   modules
          # Configure that a scope must always be provided.
          requireScope: false
          # When using "Squash and merge" on a PR with only one commit, GitHub
          # will suggest using that commit message instead of the PR title for the
          # merge commit, and it's easy to commit this by mistake. Enable this option
          # to also validate the commit message for one commit PRs.
          validateSingleCommit: true
          # choose action the way to validate pr title
          # you can choose 'comment' | 'autofix'. default is 'comment'
          # comment: comment on pr when the validation was failed
          # autofix: automatically fix pr title when validation was failed
          action: comment
