name: Auto Labeler and Reviewer Assignment

on: [pull_request_target]

jobs:
  label-and-review:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Run Labeler
      id: labeler
      uses: actions/labeler@v4
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: .github/labeler.yml

    - name: Add Reviewer for Core or Infrastructure Labels
      if: contains(steps.labeler.outputs.all-labels, 'core') || contains(steps.labeler.outputs.all-labels, 'infrastructure')
      uses: actions/github-script@v5
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          github.rest.pulls.requestReviewers({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.issue.number,
            reviewers: [context.repo.owner]
          })