name: Auto Labeler and Reviewer Assignment

on: [pull_request_target]

jobs:
  label-and-review:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Run Labeler
      id: labeler
      uses: actions/labeler@v5
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: .github/labeler.yml

    - name: Add Reviewer for Core or Infrastructure Labels
      if: contains(steps.labeler.outputs.all-labels, 'core') || contains(steps.labeler.outputs.all-labels, 'infrastructure')
      uses: actions/github-script@v7
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const prCreator = context.payload.pull_request.user.login;
          const owner = context.repo.owner;

          if (prCreator !== owner) {
            await github.rest.pulls.requestReviewers({
              owner: owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              reviewers: [owner]
            });
          } else {
            console.log('PR creator is the owner; skipping reviewer assignment.');
          }