name: Check FTL Translations

on:
  pull_request:
    paths:
      - '**/*.ftl'

jobs:
  check_translations:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
            python -m pip install --upgrade pip
            pip install fluent fluent.syntax PyYAML python-frontmatter PyGithub

    - name: Check translations
      uses: Anheledir/MissingLocaleTranslationsFTL@v1
      env:
        REFERENCE_FTL: 'BaseBotService/Locales/en.ftl'
        GITHUB_HEAD_REF: ${{ github.head_ref }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_SHA: ${{ github.sha }}
        GITHUB_EVENT_PATH: ${{ github.event_path }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
